apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: hpl-mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: ghcr.io/crambor/hpl:v0.1.7
            name: hpl
            command:
            - mpirun
            args:
            - --allow-run-as-root
            - -np
            - "1"
            - ./xhpl

            # resources:
            #   limits:
            #     cpu: 1
            #     # memory: 0.8Gi
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - image: ghcr.io/crambor/hpl:v0.1.7
            name: hpl
            # resources:
            #   limits:
            #     cpu: 1
            #     # memory: 0.4Gi